name: Test Model
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install transformers
    - name: Run tests
      run: python -m unittest discover tests/
